spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: eureka8001
  application:
    name: springcloudserviceeureka-config
server:
  port: 8001
eureka:
  instance:
    ##注册中心的ip地址
    hostname: eureka1.com
  client:
    service-url: 
      ##注册中心地址
      defaultZone: http://eureka2.com:8002/eureka/,http://eureka3.com:8003/eureka/
      #defaultZone: http://eureka1.com:${server.port}/eureka/
     ###自己是注册中心，是否要将自己注册到注册中心去,但是集群的时候需要设置为true
    register-with-eureka: false
     ###自己是注册中心，不需要去检索服务信息
    fetch-registry: false
---
spring:
  profiles: eureka8002
  application:
    name: springcloudserviceeureka-config
server:
  port: 8002
eureka:
  instance:
    ##注册中心的ip地址
    hostname: eureka2.com
  client:
    service-url: 
      ##注册中心地址
      defaultZone: http://eureka1.com:8001/eureka/,http://eureka3.com:8003/eureka/
      #defaultZone: http://eureka1.com:${server.port}/eureka/
     ###自己是注册中心，是否要将自己注册到注册中心去,但是集群的时候需要设置为true
    register-with-eureka: false
     ###自己是注册中心，不需要去检索服务信息
    fetch-registry: false    
---
spring:
  profiles: eureka8003
  application:
    name: springcloudserviceeureka-config
server:
  port: 8003
eureka:
  instance:
    ##注册中心的ip地址
    hostname: eureka3.com
  client:
    service-url: 
      ##注册中心地址
      defaultZone: http://eureka1.com:8001/eureka/,http://eureka2.com:8002/eureka/
      #defaultZone: http://eureka1.com:${server.port}/eureka/
     ###自己是注册中心，是否要将自己注册到注册中心去,但是集群的时候需要设置为true
    register-with-eureka: false
     ###自己是注册中心，不需要去检索服务信息
    fetch-registry: false  